Updated run script.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -5,8 +5,8 @@
 # Run app!
 
 # Capture caller directory and script directory.
-callingDir="$(pwd)"
-scriptDir="$(cd $(dirname "$0") && pwd)"
+calling_dir="$(pwd)"
+script_dir="$(cd $(dirname "$0") && pwd)"
 
 # Capture project to run.
 project=$1
@@ -24,45 +24,41 @@ cd code || exit 1
 
 # Build distribution and gather properties.
 # We do it in one pass for speed.
-gradleProperties=$(./gradlew "$project":build "$project":properties)
+gradle_properties=$(./gradlew "$project":build "$project":properties)
 ./gradlew "$project":build
 if test $? -ne 0; then
   echo "Build failed!"
-  cd "$callingDir"
+  cd "$calling_dir"
   exit 1
 fi
 
-# Get Gradle properties.
-# We did this already for speed. Read above.
-# gradleProperties=$(./gradlew "$project":properties)
-
 # Go back to caller directory.
-cd "$callingDir" || exit 1
+cd "$calling_dir" || exit 1
 
 # Get build directory.
-buildDir=$(echo "$gradleProperties" | sed -n 's/^buildDir: \(.*\)/\1/p')
-if test -z "$buildDir"; then
+build_dir=$(echo "$gradle_properties" | sed -n 's/^buildDir: \(.*\)/\1/p')
+if test -z "$build_dir"; then
   echo "Build directory not found!"
   exit 1
 fi
 
 # Get distribution directory.
-distsDirName=$(echo "$gradleProperties" | sed -n 's/^distsDirName: \(.*\)/\1/p')
-if test -z "$distsDirName"; then
+dist_subdir=$(echo "$gradle_properties" | sed -n 's/^distsDirName: \(.*\)/\1/p')
+if test -z "$dist_subdir"; then
   echo "Distribution directory not found!"
   exit 1
 fi
-distDir="$buildDir/$distsDirName"
+dist_dir="$build_dir/$dist_subdir"
 
 # Get application name.
-appName=$(echo "$gradleProperties" | sed -n 's/^applicationName: \(.*\)/\1/p')
-if test -z "$appName"; then
+app_name=$(echo "$gradle_properties" | sed -n 's/^applicationName: \(.*\)/\1/p')
+if test -z "$app_name"; then
   echo "Application name not found!"
   exit 1
 fi
 
 # Get version.
-version=$(echo "$gradleProperties" | sed -n 's/^version: \(.*\)/\1/p')
+version=$(echo "$gradle_properties" | sed -n 's/^version: \(.*\)/\1/p')
 if test -z "$version"; then
   echo "Version not found!"
   exit 1
@@ -70,34 +66,34 @@ fi
 
 # Get tar path.
 if test "$version" = "unspecified"; then
-  tarName="$appName.tar"
+  tar_name="$app_name.tar"
 else
-  tarName="$appName-$version.tar"
+  tar_name="$app_name-$version.tar"
 fi
-tarPath="$distDir/$tarName"
-if test -z "$tarPath"; then
+tar_path="$dist_dir/$tar_name"
+if test -z "$tar_path"; then
   echo "No distribution found!"
   exit 1
 fi
 
 # Get work dir.
-workDir="${tarPath%.tar}"
+work_dir="${tar_path%.tar}"
 
 # Remove work directory, if it exists.
-if test -d "$workDir"; then
-  rm -dr "$workDir"
+if test -d "$work_dir"; then
+  rm -dr "$work_dir"
   if test $? -ne 0; then
-    echo "Can't remove '$workDir'!"
+    echo "Can't remove '$work_dir'!"
     exit 1
   fi
 fi
 
 # Extract distribution into work dir.
-tar -xf "$tarPath" -C "$distDir"
+tar -xf "$tar_path" -C "$dist_dir"
 if test $? -gt 0; then
   echo "Tar expansion failed!"
   exit 1
 fi
 
 # Run app.
-"$workDir"/bin/"$appName" $args
+"$work_dir"/bin/"$app_name" $args
